import { promises as fs } from "node:fs";
import path from "node:path";

export type RangeKind = "point" | "regional" | "cosmopolitan";

export interface BugGeo {
  lat: number;
  lng: number;
  region: string;
  rangeKind: RangeKind;
}

const GEO_PATH = path.join(process.cwd(), "data", "bug_geo.json");

let cache: Record<string, BugGeo> | null = null;

/** Load slug → geo coordinates (generated by scripts/backfill_geo.py). */
export async function loadBugGeo(): Promise<Record<string, BugGeo>> {
  if (cache) return cache;
  try {
    cache = JSON.parse(await fs.readFile(GEO_PATH, "utf-8")) as Record<string, BugGeo>;
  } catch {
    cache = {};
  }
  return cache;
}
